package coinbase.api.v2.service;

import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.Date;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

public final class CoinbaseApiKey {
    
    private CoinbaseApiKey() {}
    
    private String accessKey;
    private String accessSign;
    private String accessTimestamp;
    
    /**
     * The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using :
     * the secret key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation). 
     * The timestamp value is the same as the CB-ACCESS-TIMESTAMP header.
     * @throws NoSuchAlgorithmException 
     * @throws InvalidKeyException 
     */
    public static CoinbaseApiKey build(String apiKey, String method, String requestPath, String requestBody) throws InvalidKeyException, NoSuchAlgorithmException {
        CoinbaseApiKey coinbaseApiKey = new CoinbaseApiKey();
        coinbaseApiKey.accessKey = apiKey;
        coinbaseApiKey.accessTimestamp = Long.toString(new Date().getTime()/1000);
        coinbaseApiKey.accessSign = encodeSign(apiKey, coinbaseApiKey.accessTimestamp + method.toUpperCase() + ((requestBody==null) ? "" : requestBody));
        return coinbaseApiKey;
    }
    
    private static String encodeSign(String secret, String message) throws NoSuchAlgorithmException, InvalidKeyException {
        Mac sha_256_HMAC = Mac.getInstance("HmacSHA256");
        SecretKeySpec secret_key = new SecretKeySpec(secret.getBytes(), "HmacSHA256");
        sha_256_HMAC.init(secret_key);
        return Base64.getEncoder().encodeToString(sha_256_HMAC.doFinal(message.getBytes()));
    }

    public String getAccessKey() {
        return accessKey;
    }

    public String getAccessSign() {
        return accessSign;
    }

    public String getAccessTimestamp() {
        return accessTimestamp;
    }
    
}
